In [ ]:
impprt numpy as np

In [6]:
simple_list = [1,2,3]
np.array(simple_list)

In [7]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
list_of_lists=[1,2,3],[4,5,6],[7,8,9]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(10,32)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31])

In [10]:
np.arange(10,80,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74])

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [15]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [18]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
np.random.rand(2,4)

array([[0.13697962, 0.24512389, 0.30509477, 0.9490854 ],
       [0.44436154, 0.09957831, 0.78635535, 0.21157622]])

In [20]:
np.random.randint(10,100,15)

array([82, 33, 89, 35, 52, 64, 29, 97, 52, 76, 56, 66, 73, 28, 25])

In [21]:
np.random.randint(0,10,15)

array([7, 8, 2, 6, 5, 1, 7, 1, 7, 2, 6, 3, 7, 3, 4])

In [23]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
rand_array=np.random.randint(0,10,5)
rand_array

array([3, 1, 4, 5, 7])

In [26]:
sample_array.min()

2